### ISSUE TITLE
In case of single select mode, it returns me array

### ISSUE THREAD

**Issue by harpal-singh1** [blackbaud/skyux-lookup#209]
### Expected behavior
If I'm working with single select mode, It should give me single value not an array with single value

### Actual behavior
https://stackblitz.com/run?file=src%2Fapp%2Flookup-single-demo.component.ts
```
 public name: any[] = [
    { name: 'Shirley' }
  ];
```
name is array of name, looks weird.

### Steps to reproduce
https://stackblitz.com/run?file=src%2Fapp%2Flookup-single-demo.component.ts

### Impact
It's impact could be high, because I already made it by fixes to convert single value to array and while getting it taking value at first index.

**Comment by Blackbaud-TrevorBurch** [comment]
Hi @harpal-singh1 - This returns an array by design due to backwards compatibility. We also allow consumers to switch modes dynamically if need and the array allows consumers to expect a consistent return value for each mode. Because of these considerations, we will not be changing this API at this time.
